info:
  contact: {}
paths:
  /api/v1/hello:
    get:
      description: Hello from v1
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Say Hello (V1)
      tags:
      - v1
  /api/v2/hello:
    get:
      description: Hello from v2 (new logic)
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Say Hello (V2)
      tags:
      - v2
swagger: "2.0"
