definitions:
  entity.Customer:
    properties:
      account_num:
        type: string
      biller_id:
        type: string
      company_bank:
        type: string
      customer_status:
        type: integer
      modified_datetime:
        type: string
      name:
        type: string
    type: object
  entity.FileExistResponse:
    properties:
      exists:
        type: boolean
    type: object
  entity.FileInfo:
    properties:
      mod_time:
        type: string
      name:
        type: string
    type: object
  entity.GenerateQRRequest:
    properties:
      path:
        type: string
      qr:
        type: string
    required:
    - path
    - qr
    type: object
  entity.GenerateStringRequest:
    properties:
      account_num:
        type: string
      amount:
        type: string
      biller_id:
        type: string
      company_bank:
        type: string
    required:
    - account_num
    - amount
    - biller_id
    - company_bank
    type: object
info:
  contact: {}
paths:
  /api/v1/customers:
    get:
      consumes:
      - application/json
      description: คืนค่าข้อมูลลูกค้าที่แอคทีฟหรือ Re-Active ในสัปดาห์ปัจจุบัน (ตาม
        MSSQL)
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Customer'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: รายชื่อลูกค้าแอคทีฟในสัปดาห์นี้
      tags:
      - v1-GET
  /api/v1/file-exist:
    get:
      consumes:
      - application/json
      description: ตรวจสอบว่าไฟล์ path นี้มีอยู่จริงไหม
      parameters:
      - description: File path
        in: query
        name: path
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.FileExistResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Check file exist
      tags:
      - v1-GET
  /api/v1/files:
    get:
      consumes:
      - application/json
      description: Show filename and last modified time in a directory
      parameters:
      - description: Directory path
        in: query
        name: path
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.FileInfo'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: List files in directory
      tags:
      - v1-GET
  /api/v1/generate:
    post:
      consumes:
      - application/json
      description: Generate string from input params
      parameters:
      - description: Request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/entity.GenerateStringRequest'
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Generate String
      tags:
      - v1-POST
  /api/v1/hello:
    get:
      description: Hello from v1
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Say Hello (V1)
      tags:
      - v1-GET
  /api/v1/qr:
    post:
      consumes:
      - application/json
      description: สร้างไฟล์ QR Code PNG จาก text
      parameters:
      - description: ข้อมูล QR
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/entity.GenerateQRRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Generate QR Code
      tags:
      - v1-POST
  /api/v2/hello:
    get:
      description: Hello from v2 (new logic)
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Say Hello (V2)
      tags:
      - v2
swagger: "2.0"
