basePath: /
host: localhost:8080
info:
  contact: {}
  description: This is a sample server.
  title: Example API
  version: "1.0"
paths:
  /hello:
    get:
      description: Respond with hello world
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Say Hello
      tags:
      - example
swagger: "2.0"
